django_project/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import urls as ur
from django_project import views
from accounts import views as vi
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls import url
from .views import Home
app_mname='django_project'
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index.html'),
    url(r'^about/$',views.about,name='about.html'),
    url(r'^courses/$',views.courses,name='courses.html'),
    url(r'^teacher/$',views.teacher,name='teacher.html'),
    url(r'^jobs/$',views.jobs,name='jobs.html'),
    url(r'^test/$',views.test,name='test.html'),
    url(r'^contact/$',views.contact,name='contact.html'),
    path('accounts/', include('allauth.urls')),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('register/', vi.RegisterView.as_view(), name='register'),
    #path('', Home.as_view(), name='home'),
    path('about/', TemplateView.as_view(
        template_name='about_us.html'
    ), name='about_us'),
    path('courses/ml/',views.ml,name='machine.html#ml'),
    
    path('courses/data/',views.data,name='machine.html#dsa'),

    path('courses/iot/',views.iot,name='machine.html#iot'),

    path('courses/polsci/',views.polsci,name='machine.html#ps'),

    path('courses/eeng/',views.eeng,name='machine.html#ee'),

    path('courses/mmanage/',views.mmanage,name='machine.html#mm'),

    path('courses/gdesign/',views.gdesign,name='machine.html#gd'),

    path('courses/hrmanage/',views.hrmanage,name='machine.html#hrm'),


    path('personality/', include('personality.urls')),
    path('', include('accounts.urls')),

    path('payment/', include('payment.urls')),
]

payment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.pay, name='pay'),
    path('success' , views.success , name='pay-success')
]

personality/urls.py
from os import name
from personality.views import modalPage
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.conf.urls import url

from personality import views

urlpatterns = [
    path('modalPage', views.modalPage, name='modal'),
    path('detect', views.capture, name='facedetect'),
    path('home/', login_required (TemplateView.as_view(
        template_name='personality/home.html'
    )), name='personality_home'),
    path('aptitude_test/', login_required(TemplateView.as_view(
        template_name='personality/aptitude_home.html')),
        name='aptitude_home'),
    path('aptitude/test/', views.AptitudeTest.as_view(), name='aptitude_test'),
    path('aptitude/finished/', TemplateView.as_view(
        template_name='personality/aptitude_finished.html'),
        name='aptitude_finished'),
    path('test/', views.PersonalityTest.as_view(), name='personality_test'),
    path('completed/', views.PersonalityCompleted.as_view(), name='personality_completed'),
    path('index/', login_required (TemplateView.as_view(
        template_name='personality/index.html'
    )), name='index'),
     path('team/', views.team, name='team.html'),
    #re_path(r'^admin/',admin.site.urls),
    #url(r'^admin/',admin.site.urls,name='admin'),

]

personality/models.py
from django.db import models


class PersonalityType(models.Model):
    name   = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class PersonalityQuestion(models.Model):
    question_text   = models.CharField(max_length=100)
    category        = models.ForeignKey(PersonalityType, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text


class TestQuestion(models.Model):
    question_text   = models.CharField(max_length=100)

    def __str__(self):
        return self.question_text
    
    class Meta:
        ordering = ['?']


class TestChoice(models.Model):
    choice_text = models.CharField(max_length=100)
    question    = models.ForeignKey(TestQuestion, on_delete=models.CASCADE)
    is_answer   = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

personality/views.py
from django_project.settings import BASE_DIR
import os
import pickle
import numpy as np
import pandas as pd
import cv2
import sys
import time

from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model

from .models import TestQuestion, TestChoice, PersonalityType, PersonalityQuestion
from .utils import clear_test_session

User = get_user_model()
classifer_base = os.path.join(settings.BASE_DIR, 'personality', 'classifiers')

class AptitudeTest(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if not request.user.applicant.taken_apt_test and not request.user.is_staff:
            qs = TestQuestion.objects.all()[:10]

            context = {
                'questions': qs
            }
        else:
            context = {}
        return render(request, 'personality/aptitude_test.html', context)

    def post(self, request, *args, **kwargs):
        if not request.user.applicant.taken_apt_test and not request.user.is_staff:
            choices = [request.POST.get(str(q+1)) for q in range(10)]
            score = 0
            user_choices = TestChoice.objects.filter(pk__in=choices)
            correct_answers = TestChoice.objects.filter(is_answer=True)
            correct_ids = [x.id for x in correct_answers]
            for uc in user_choices:
                if(uc.id in correct_ids):
                    score += 10
            print(score)
            user = User.objects.get(username=request.user.username)
            user.applicant.test_score = score
            user.applicant.taken_apt_test = True
            #user.applicant.is_employable="NULL"
            user.applicant.save()
            return redirect('aptitude_finished')
        else:
            return render(request, 'personality/aptitude_test.html', {})

fscores = []
class PersonalityTest(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if not request.user.applicant.taken_personality_test and not request.user.is_staff:
            qs = PersonalityType.objects.all()
            type_o = PersonalityType.objects.get(id=1)
            type_c = PersonalityType.objects.get(id=2)
            type_e = PersonalityType.objects.get(id=3)
            type_a = PersonalityType.objects.get(id=4)
            type_n = PersonalityType.objects.get(id=5)

            context = {
                'type_o': type_o,
                'type_c': type_c,
                'type_e': type_e,
                'type_a': type_a,
                'type_n': type_n,
            }
        else:
            context = {}
        return render(request, 'personality/personality_test.html', context)

    def post(self, request, *args, **kwargs):
        if not request.user.applicant.taken_personality_test and not request.user.is_staff:
            request_count = len(request.POST)-2
            choices = [int(request.POST.get('choice'+str(q+1))) for q in range(request_count)]
            print(choices)
            average = sum(choices)/len(choices) if len(choices) > 0 else 0

            print(average)
            type_o = PersonalityType.objects.get(id=1)
            type_c = PersonalityType.objects.get(id=2)
            type_e = PersonalityType.objects.get(id=3)
            type_a = PersonalityType.objects.get(id=4)
            type_n = PersonalityType.objects.get(id=5)
            user = User.objects.get(username=request.user.username)

            test_type = request.POST.get('test_type')

            if test_type == '1':
                print('Openness Test')
                request.session['avg_o'] = sum(choices)/len(choices)
                f5 = 8 + choices[0]-choices[1]+choices[2]-choices[3]+choices[4]-choices[5]+choices[6]+choices[7]+choices[8]+choices[9]
                if(f5<20):
                    f5str = 'I'
                else:
                    f5str = 'N'
                print("F5 : ")
                print(f5)
                print(f5str)
                fscores.append(f5str)
                answers = pd.DataFrame([choices])

                request.session['done_o'] = True
            elif test_type == '2':
                print('Consientious Test')
                request.session['avg_c'] = sum(choices)/len(choices)
                f3 = 14 + choices[0]-choices[1]+choices[2]-choices[3]+choices[4]-choices[5]+choices[6]-choices[7]+choices[8]+choices[9]

                if(f3<20):
                    f3str = 'O'
                else:
                    f3str = 'U'
                print("F3 : ")
                print(f3)
                print(f3str)
                fscores.append(f3str)    #pickle_in = open(os.path.join(classifer_base, 'conscientious.pkl'), 'rb')
                answers = pd.DataFrame([choices])
                request.session['done_c'] = True
            elif test_type == '3':
                print('Extroversion Test')
                request.session['avg_e'] = sum(choices)/len(choices)
                f1 = 20 + choices[0]-choices[1]+choices[2]-choices[3]+choices[4]-choices[5]+choices[6]-choices[7]+choices[8]-choices[9]

                if(f1<20):
                    f1str = 'S'
                else:
                    f1str = 'R'
                print("F1 : ")
                print(f1)
                print(f1str)
                fscores.append(f1str)
                answers = pd.DataFrame([choices])
                request.session['done_e'] = True
            elif test_type == '4':
                print('Agreeable Test')
                request.session['avg_a'] = sum(choices)/len(choices)
                f4 = sum(choices)
                f4 = 14 - choices[0]+choices[1]-choices[2]+choices[3]-choices[4]+choices[5]-choices[6]+choices[7]+choices[8]+choices[9]

                if(f4<20):
                    f4str = 'A'
                else:
                    f4str = 'E'
                print("F4 : ")
                print(f4)
                print(f4str)
                fscores.append(f4str)
                answers = pd.DataFrame([choices])

                #result = clf_agb.predict(answers)
                #user.applicant.personality.add(type_a) if result == ['YES'] else None
                request.session['done_a'] = True
            elif test_type == '5':
                print('Neurotism Test')
                request.session['avg_n'] = sum(choices)/len(choices)
                f2 = 38 - choices[0]+choices[1]-choices[2]+choices[3]-choices[4]-choices[5]-choices[6]-choices[7]-choices[8]-choices[9]

                if(f2<20):
                    f2str = 'C'
                else:
                    f2str = 'L'
                print("F2 : ")
                print(f2)
                print(f2str)
                fscores.append(f2str)
                answers = pd.DataFrame([choices])

                request.session['done_n'] = True

                user.applicant.taken_personality_test = True
                user.applicant.save()

                return redirect('personality_completed')


        return redirect('personality_test')


class PersonalityCompleted(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.user.applicant.taken_personality_test and not request.user.is_staff:
            avg_o = request.session.get('avg_o', None)
            avg_c = request.session.get('avg_c', None)
            avg_e = request.session.get('avg_e', None)
            avg_a = request.session.get('avg_a', None)
            avg_n = request.session.get('avg_n', None)
            averages = [avg_o, avg_c, avg_e, avg_a, avg_n]
            print(averages)
            if len(averages) != 5 or None in averages:
                completed = False
            else:
                personality_avgs = pd.DataFrame([averages])
                #result = clf_emp.predict(personality_avgs)
                #print('Employable', result)
                possible_results = [1,0]
                #if result in possible_results:
                completed = True
                clear_test_session(request)
                user = User.objects.get(username=request.user.username)
                f1str = fscores[2]
                f2str = fscores[4]
                f3str = fscores[1]
                f4str = fscores[3]
                f5str = fscores[0]
                str = f1str+f2str+f3str+f4str+f5str
                print(str)
                user.applicant.is_employable = str
                user.applicant.save()
        else:
            completed = False
        context = {
            'completed': completed
        }
        return render(request, 'personality/personality_completed.html', context)
        
def team(request):
    return render(request,'team.html')


cascPath = sys.argv[1]
faceCascade = cv2.CascadeClassifier(cascPath)
face_classifier = cv2.CascadeClassifier(os.path.join(BASE_DIR,'haarcascade_frontalface_default.xml'))

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image  
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)

    if faces is ():
        return None

    # Crop all faces found
    for (x,y,w,h) in faces:
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face


def capture(request):
    video_capture = cv2.VideoCapture(0)

    ##4.35seconds
    found = False
    start = time.time()
    while int(time.time()-start) <= 7:
        # Capture frame-by-frame
        ret, frame = video_capture.read()
        if (ret):
            if face_extractor(frame) is not None:            
                gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

                faces = face_classifier.detectMultiScale(gray, 1.3, 5)
                # Draw a rectangle around the faces
                for (x, y, w, h) in faces:

personality/templates/personality/aptitude_finished.html
{% extends "base.html" %}


{% block content %}
  <center>
      <div class="congo-back-img">
          <h1 class="congo-heading">CONGRATULATIONS !!</h1>
          <p class="congo-content">Next, You have to take a personaility test. Please be sincere with your answers.</p>
          <div><a class="congo-button" href="{% url 'personality_test' %}">Take Your Personality Test</a></div>
      </div>
  </center>

{% endblock content %}

personality/templates/personality/aptitude_home.html
{% extends 'base.html' %}


{% block content %}
<br>
  <center>

      <br>
<div class="container">
    <div class="col-12 mx-auto py-5 text-center">
        <h2>Aptitude Test</h2>
        <p>The aptitude tests consists of 10 compulsory questions. </p>
        <a href="{% url 'aptitude_test' %}" class="btn btn-primary btn-lg">Begin</a>
    </div>
</div>

  </center>
      <br>
{% endblock content %}

personality/templates/personality/aptitude_test.html
{% extends 'base.html' %}


{% block content %}
<br>
  <center>

      <br>
<div class="container">
    {% if not request.user.applicant.taken_apt_test %}
        <form action="" method="post">
            {% csrf_token %}

            {% for question in questions %}
                <div class="card" style="margin: 20px 0;">
                    <div class="card-body">
                        <h4 class="card-title">{{forloop.counter}}) {{ question.question_text }}</h4>
                        {% for choice in question.testchoice_set.all %}
                            <input type="radio" name="{{forloop.parentloop.counter}}" id="choice{{ choice.id }}" value="{{ choice.id }}" required />
                            <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br />
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

            <div class="d-flex justify-content-end" style="margin: 40px 0;">
                <input type="submit" class="btn btn-danger btn-lg" value="Submit" />
            </div>

        </form>
    {% else %}
        <h2>You have already taken your aptitude test. You can't take it twice</h2>
    {% endif %}

</div>

  </center>

      <br>
{% endblock content %}

personality/templates/personality/face_fail.html
{% extends 'base.html' %}


{% block content %}
<br>
  <center>
<div class="faceD-back-img" style="background-image: url('/static/images/wrong-1.jpg');">
    <h1 class="congo-heading" style="color: black; padding-top: 60px;">Sorry {{ request.user.username }}</h1>
    <p class="congo-content" style="margin-top: 267px; color: aliceblue">Unable to detect your face! Try Again!</p>
    <div><a class="btn btn-primary btn-lg" style="margin-top:; background: #5d50c6;" href="{% url 'home.html' %}">Retry</a></div>
</div>
  </center>
      <br>
{% endblock content %}

personality/templates/personality/face_pass.html
{% extends 'base.html' %}


{% block content %}
<br>
  <center>
<div class="faceD-back-img" style="background-image: url('/static/images/right-1.jpg');">
    <h1 class="congo-heading" style="color: black; padding-top: 50px;">Congratulation {{ request.user.username }}</h1>
    {% if not request.user.applicant.taken_apt_test %}
    <div><a class="btn btn-primary btn-lg" style="margin-top: 267px; background: #5d50c6;" href="/personality/detect">Aptitude Test</a></div> <!--previous href: {% url 'aptitude_test' %}-->
    {% elif not request.user.applicant.taken_personality_test %}
    <div><a class="btn btn-primary btn-lg" href="/personality/detect">Personality Test</a></div> <!--previous href: {% url 'personality_test' %}-->
    {% endif %}
</div>
  </center>
      <br>
{% endblock content %}

personality/templates/personality/home.html
{% extends 'base.html' %}


{% block content %}
<br>
  <center>
<div class="congo-back-img">
    <h1 class="congo-heading">Hello {{ request.user.username }}</h1>
    <p class="congo-content">You are to complete an aptitude and personality test.</p>
    {% if not request.user.applicant.taken_apt_test %}
    <div><a class="congo-button" href="/personality/modalPage">Aptitude Test</a></div>
    {% elif not request.user.applicant.taken_personality_test %}
    <div><a class="congo-button" href="/personality/modalPage">Take Your Personality Test</a></div>
    {% else %}
    <div class="alert alert-info messages" style="width: 75%; margin-top: 100px;">
        <span class="alert-info">
            You have already completed all tests. We would get back to you via email, Thanks.
        </span>
    </div>
    {% endif %}
</div>
  </center>
      <br>
{% endblock content %}

personality/templates/personality/personality_completed.html
{% extends "base.html" %}


{% block content %}

  <center>
  
      <br>
    <div class="container">

        {% if completed %}
            <div class="congo-back-img">
                <h1 class="congo-heading">You're Done</h1>
                <p class="congo-content">Thank You for taking your time to take these test. We would get back to you through the email you provided.</p>
                <div><a class="congo-button" href="{% url 'logout' %}">Logout</a></div>
            </div>
        {% else %}
            <h4>Oopss!!</h4>
            <p>Something went wrong. Contact the admin if this problem persists.</p>
        {% endif %}


    </div>

      </center>

          <br>
{% endblock content %}

personality/templates/personality/personality_test.html
{% extends 'base.html' %}


{% block content %}

<br>
<center>
    <div class="container">
        <!-- <p>Avg: {{request.session.avg_o}} Done: {{request.session.done_o|default:False}}</p>
        <p>Avg: {{request.session.avg_c}} Done: {{request.session.done_c|default:False}}</p>
        <p>Avg: {{request.session.avg_e}} Done: {{request.session.done_e|default:False}}</p>
        <p>Avg: {{request.session.avg_a}} Done: {{request.session.done_a|default:False}}</p>
        <p>Avg: {{request.session.avg_n}} Done: {{request.session.done_n|default:False}}</p> -->

        {% if not request.user.applicant.taken_personality_test %}
            {% if not request.session.done_o|default:False %}
                <h1>{{type_o.name}}</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="test_type" value="{{ type_o.id }}">
                    {% include "personality/snippets/personality_choices.html" with personality_type=type_o %}
                    <div class="d-flex justify-content-end" style="margin: 40px 0;">
                        <input type="submit" class="btn btn-danger btn-lg" value="Next" />
                    </div>
                </form>
            {% elif not request.session.done_c|default:False %}
                  <h1>{{type_c.name}}  </h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="test_type" value="{{ type_c.id }}">
                    {% include "personality/snippets/personality_choices.html" with personality_type=type_c %}
                    <div class="d-flex justify-content-end" style="margin: 40px 0;">
                        <input type="submit" class="btn btn-danger btn-lg" value="Next" />
                    </div>
                </form>
            {% elif not request.session.done_e|default:False %}
                  <h1>{{type_e.name}}  </h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="test_type" value="{{ type_e.id }}">
                    {% include "personality/snippets/personality_choices.html" with personality_type=type_e %}
                    <div class="d-flex justify-content-end" style="margin: 40px 0;">
                        <input type="submit" class="btn btn-danger btn-lg" value="Next" />
                    </div>
                </form>
            {% elif not request.session.done_a|default:False %}
                  <h1>{{type_a.name}}  </h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="test_type" value="{{ type_a.id }}">
                    {% include "personality/snippets/personality_choices.html" with personality_type=type_a %}
                    <div class="d-flex justify-content-end" style="margin: 40px 0;">
                        <input type="submit" class="btn btn-danger btn-lg" value="Next" />
                    </div>
                </form>
            {% elif not request.session.done_n|default:False %}
                <h1>  {{type_n.name}}  </h1>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="test_type" value="{{ type_n.id }}">
                    {% include "personality/snippets/personality_choices.html" with personality_type=type_n %}
                    <div class="d-flex justify-content-end" style="margin: 40px 0;">
                        <input type="submit" class="btn btn-danger btn-lg" value="Next" />
                    </div>
                </form>
            {% endif %}
        {% else %}
            <div class="congo-back-img">
                <h1 class="congo-heading">You're Done</h1>
                <p class="congo-content">You have already taken your personality test. You can't take it twice.</p>
            </div>
        {% endif %}

    </div>

  </center>

      <br>
{% endblock content %}